export enum AnalyticsEnum {
  APP_INIT = 'APP_INIT',

  NAVBAR_LOGO = 'NAVBAR_LOGO',
  NAVBAR_TEXT = 'NAVBAR_TEXT',

  FOOTER_GITHUB = 'FOOTER_GITHUB',
  FOOTER_LINKEDIN = 'FOOTER_LINKEDIN',
  FOOTER_INSTAGRAM = 'FOOTER_INSTAGRAM',

  CATEGORIES_INIT = 'CATEGORIES_INIT',
  CATEGORIES_BACK = 'CATEGORIES_BACK',
  CATEGORIES_INIT_FROM_EXPENSES = 'CATEGORIES_INIT_FROM_EXPENSES',
  CATEGORIES_NEW = 'CATEGORIES_NEW',
  CATEGORIES_REQUIRED_FIELDS = 'CATEGORIES_REQUIRED_FIELDS',
  CATEGORIES_SAVE = 'CATEGORIES_SAVE',
  CATEGORIES_CREATED = 'CATEGORIES_CREATED',
  CATEGORIES_EDIT = 'CATEGORIES_EDIT',
  CATEGORIES_EDITED = 'CATEGORIES_EDITED',
  CATEGORIES_DELETE = 'CATEGORIES_DELETE',
  CATEGORIES_DELETED = 'CATEGORIES_DELETED',

  EXPENSES_INIT = 'EXPENSES_INIT',
  EXPENSES_BACK = 'EXPENSES_BACK',
  EXPENSES_NEW = 'EXPENSES_NEW',
  EXPENSES_REQUIRED_FIELDS = 'EXPENSES_REQUIRED_FIELDS',
  EXPENSES_SAVE = 'EXPENSES_SAVE',
  EXPENSES_CREATED = 'EXPENSES_CREATED',
  EXPENSES_EDIT = 'EXPENSES_EDIT',
  EXPENSES_EDITED = 'EXPENSES_EDITED',
  EXPENSES_DELETE = 'EXPENSES_DELETE',
  EXPENSES_DELETED = 'EXPENSES_DELETED',
}
